name: build-mac

on:
  workflow_dispatch: {}        # para correrlo manualmente
  push:
    tags: ['v*.*.*']           # opcional: se ejecuta al crear un tag v1.0.0

jobs:
  mac:
    strategy:
      matrix:
        include:
          - runner: macos-14   # Apple Silicon (M1/M2/M3)
            arch: arm64
          - runner: macos-13   # Intel
            arch: x64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Prepare deps (mac optional deps workaround)
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm cache clean --force
          npm install --no-audit --no-fund

      - name: Disable code signing
        run: echo "CSC_IDENTITY_AUTO_DISCOVERY=false" >> $GITHUB_ENV

      - name: Build (macOS ${{ matrix.arch }})
        env:
          CI: ""   # evita auto-publicar por estar en CI
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            npx quasar build -m electron -- --mac dmg --arm64 --publish never
          else
            npx quasar build -m electron -- --mac dmg --x64 --publish never
          fi


      - name: Upload artifacts (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: expediente-mac-${{ matrix.arch }}
          path: dist/electron/Packaged/**
          if-no-files-found: error
          retention-days: 14
